Introducing kqml: QML runtime with initialized KLocalizedContext
Useful for testing scratch files that either directly or via imported
modules assume that KLocalizedString domain has been set and
KLocalizedContext initialized, so they can rely on family of i18n*
functions being available in QML scope. In other words, for loading any
real-world KDE QML source file without getting these errors:

> ReferenceError: i18n is not defined

This simple application is very similar to `qml` and `qmlscene` tools
provided by qt-declarative package. But unlike those tools kqml is very
minimal, without any of the advanced options, custom containment
configs or things like OS X specific platform workarounds. Those things
can always be added back later if desired, but so far I personally
never heard of anyone who would use any of `qml` options beyond passing
it a single *.qml file. Except… maybe a --slow-animations which we
can't implement anyway without including private API bits.

This new tool comes with documentation (man page) and zsh completions.